name: Deploy Blog

on:
  push:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Nodejs 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Dependencies
        shell: bash
        run: yarn
      - name: Predeploy
        shell: bash
        run: yarn predeploy
      - name: test
        shell: bash
        run: echo 'test'
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GH_PAT}}
          publish_branch: master
          publish_dir: ./public
